name: Daily Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run at midnight every day

jobs:
  full-coverage:
    name: Unit test and integration test coverage analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cargo check
        run: |
          cargo update
          cargo check
